In [1]:
import numpy as np
import pandas as pd

# 9.3.5 例子：组加权平均和相关性

In [2]:
df = pd.DataFrame({'category': ['a', 'a', 'a', 'a',
                                'b', 'b', 'b', 'b'],
                   'data': np.random.randn(8),
                   'weights': np.random.rand(8)})
df

  category      data   weights
0        a -1.598294  0.175344
1        a -0.492466  0.095003
2        a  0.431356  0.386671
3        a -1.040744  0.958203
4        b -1.678837  0.091632
5        b  1.069417  0.035678
6        b -0.023899  0.862164
7        b  0.302808  0.452014

按category分组来计算组加权平均：

In [3]:
grouped = df.groupby('category')
get_wavg = lambda g: np.average(g['data'], weights=g['weights'])
grouped.apply(get_wavg)

category
a   -0.716613
b    0.000408
dtype: float64

In [4]:
close_px = pd.read_csv('../examples/stock_px_2.csv',parse_dates=True,index_col=0)
close_px.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2214 entries, 2003-01-02 to 2011-10-14
Data columns (total 4 columns):
AAPL    2214 non-null float64
MSFT    2214 non-null float64
XOM     2214 non-null float64
SPX     2214 non-null float64
dtypes: float64(4)
memory usage: 86.5 KB

In [17]:
close_px.head()

            AAPL   MSFT    XOM     SPX
2003-01-02  7.40  21.11  29.22  909.03
2003-01-03  7.45  21.14  29.24  908.59
2003-01-06  7.45  21.52  29.96  929.01
2003-01-07  7.43  21.93  28.95  922.93
2003-01-08  7.28  21.31  28.83  909.93

In [18]:
close_px.pct_change().head()

                AAPL      MSFT       XOM       SPX
2003-01-02       NaN       NaN       NaN       NaN
2003-01-03  0.006757  0.001421  0.000684 -0.000484
2003-01-06  0.000000  0.017975  0.024624  0.022474
2003-01-07 -0.002685  0.019052 -0.033712 -0.006545
2003-01-08 -0.020188 -0.028272 -0.004145 -0.014086

In [19]:
rets = close_px.pct_change().dropna()
rets.head()

                AAPL      MSFT       XOM       SPX
2003-01-03  0.006757  0.001421  0.000684 -0.000484
2003-01-06  0.000000  0.017975  0.024624  0.022474
2003-01-07 -0.002685  0.019052 -0.033712 -0.006545
2003-01-08 -0.020188 -0.028272 -0.004145 -0.014086
2003-01-09  0.008242  0.029094  0.021159  0.019386

In [20]:
get_year = lambda x: x.year
by_year = rets.groupby(get_year)
for i, j in by_year:
    print(i, j, sep='\n')
    print()

2003
                AAPL      MSFT       XOM       SPX
2003-01-03  0.006757  0.001421  0.000684 -0.000484
2003-01-06  0.000000  0.017975  0.024624  0.022474
2003-01-07 -0.002685  0.019052 -0.033712 -0.006545
2003-01-08 -0.020188 -0.028272 -0.004145 -0.014086
2003-01-09  0.008242  0.029094  0.021159  0.019386
2003-01-10  0.002725  0.001824 -0.013927  0.000000
2003-01-13 -0.005435  0.008648 -0.004134 -0.001412
2003-01-14 -0.002732  0.010379  0.008993  0.005830
2003-01-15 -0.010959 -0.012506 -0.013713 -0.014426
2003-01-16  0.012465 -0.016282  0.004519 -0.003942
2003-01-17 -0.035568 -0.070345 -0.010381 -0.014017
2003-01-21 -0.005674 -0.002473 -0.023077 -0.015702
2003-01-22 -0.009986 -0.006445 -0.012885 -0.010432
2003-01-23  0.021614  0.024950 -0.002175  0.010224
2003-01-24 -0.026798 -0.046251 -0.021439 -0.029233
2003-01-27  0.024638 -0.013783 -0.026736 -0.016160
2003-01-28  0.031117 -0.007246  0.026326  0.013050
2003-01-29  0.024691  0.022419  0.036431  0.006779
2003-01-30 -0.041499 -0.033656 -0.018293 -0.022849
2003-01-31  0.002793 -0.015831  0.027768  0.013130
2003-02-03  0.020891  0.023056  0.013864  0.005399
2003-02-04 -0.004093 -0.025681  0.000000 -0.014088
2003-02-05 -0.010959 -0.007531 -0.014376 -0.005435
2003-02-06  0.000000  0.009756 -0.008538 -0.006449
2003-02-07 -0.020776 -0.017713 -0.007535 -0.010094
2003-02-10  0.015559  0.017486  0.007592  0.007569
2003-02-11  0.000000 -0.019871 -0.007176 -0.008098
2003-02-12  0.002786  0.000000 -0.019877 -0.012687
2003-02-13  0.009722  0.011507  0.012906 -0.001600
2003-02-14  0.009629  0.028169  0.009465  0.021435
...              ...       ...       ...       ...
2003-11-18 -0.034091  0.000000 -0.012604 -0.009084
2003-11-19  0.000980  0.008024  0.008062  0.008016
2003-11-20 -0.001959 -0.009950 -0.003665 -0.008432
2003-11-21 -0.004907  0.000503  0.001003  0.001577
2003-11-24  0.042406  0.024611  0.006014  0.016227
2003-11-25 -0.021760 -0.012745  0.007307  0.001720
2003-11-26  0.001934  0.001986  0.012859  0.004327
2003-11-28  0.008687  0.009911 -0.002279 -0.000236
2003-12-01  0.038278  0.005397  0.005546  0.011264
2003-12-02 -0.007373 -0.007321  0.002920 -0.003271
2003-12-03 -0.023213  0.000492  0.000971 -0.001772
2003-12-04  0.004753  0.020639  0.013251  0.004687
2003-12-05 -0.013245 -0.008185 -0.006380 -0.007684
2003-12-08  0.008629  0.009709  0.016693  0.007348
2003-12-09 -0.027567  0.005288  0.006315 -0.008529
2003-12-10 -0.003910  0.008130  0.004079 -0.001066
2003-12-11  0.040236  0.000949  0.003125  0.011482
2003-12-12 -0.015094  0.001422  0.004050  0.002735
2003-12-15 -0.033525  0.003313 -0.006826 -0.005679
2003-12-16 -0.002973  0.011792  0.017807  0.006638
2003-12-17 -0.011928 -0.000466  0.010436  0.001256
2003-12-18  0.008048  0.013060  0.013670  0.011798
2003-12-19 -0.016966 -0.001381  0.004795 -0.000477
2003-12-22  0.008122 -0.006455 -0.003281  0.003931
2003-12-23 -0.003021 -0.001392  0.007181  0.002818
2003-12-24  0.030303 -0.003717  0.002080 -0.001807
2003-12-26  0.018627  0.006063  0.005336  0.001691
2003-12-29  0.017324  0.009272  0.013270  0.012401
2003-12-30  0.006623  0.002297  0.002619  0.000144
2003-12-31  0.004699 -0.005500  0.007837  0.002055

[251 rows x 4 columns]

2004
                AAPL      MSFT       XOM       SPX
2004-01-02 -0.004677  0.002765 -0.008929 -0.003094
2004-01-05  0.042293  0.025276  0.023249  0.012395
2004-01-06 -0.003607  0.003586 -0.006816  0.001292
2004-01-07  0.022624 -0.001340 -0.007149  0.002367
2004-01-08  0.033628 -0.001342 -0.002592  0.004963
2004-01-09 -0.015411 -0.017913 -0.014727 -0.008888
2004-01-12  0.031304 -0.003192  0.014068  0.004787
2004-01-13  0.016863 -0.005032 -0.004335 -0.005332
2004-01-14  0.003317  0.009655  0.000000  0.008295
2004-01-15 -0.055372 -0.005920 -0.009869  0.001353
2004-01-16 -0.006124  0.010078  0.005570  0.006872
2004-01-20  0.000000  0.010431  0.009329 -0.000930
2004-01-21 -0.004401  0.007181  0.013287  0.007772
2004-01-22 -0.019452 -0.010250 -0.003421 -0.003207
2004-01-23  0.017133  0.016659 -0.006007 -0.002089
2004-01-26  0.020390  0.011072  0.012374  0.012106
2004-01-27  0.001738 -0.018835 -0.008528 -0.009798
2004-01-28 -0.023417 -0.019196 -0.009174 -0.013610
2004-01-29  0.007105  0.007283  0.016204  0.004989
2004-01-30 -0.005291 -0.009489 -0.016515 -0.002628
2004-02-02 -0.010638 -0.009124 -0.002316  0.003651
2004-02-03 -0.002688 -0.003683 -0.006965  0.000678
2004-02-04 -0.020665 -0.010628 -0.001461 -0.008371
2004-02-05  0.028440 -0.001868  0.000585  0.001838
2004-02-06  0.012489  0.004679  0.003217  0.012555
2004-02-09 -0.000881 -0.006521  0.011662 -0.002581
2004-02-10  0.013228  0.004219  0.008934  0.005027
2004-02-11  0.035683  0.004669  0.020280  0.010667
2004-02-12 -0.003361 -0.006970 -0.000280 -0.004880
2004-02-13 -0.030354 -0.013570  0.000000 -0.005468
...              ...       ...       ...       ...
2004-11-18  0.008743 -0.003738  0.000922  0.001362
2004-11-19 -0.003973 -0.007920  0.006680 -0.011161
2004-11-22  0.112038 -0.007563  0.010526  0.005896
2004-11-23 -0.000978 -0.004657  0.005661 -0.000255
2004-11-24  0.045366  0.004254  0.005629  0.004095
2004-11-26  0.007805 -0.001694  0.003135  0.000753
2004-11-29  0.060099  0.006364 -0.005357 -0.003450
2004-11-30 -0.020164  0.001686 -0.002469 -0.004030
2004-12-01  0.011035  0.016414 -0.001800  0.014951
2004-12-02 -0.038348 -0.005797 -0.019157 -0.000873
2004-12-03 -0.038650  0.004998  0.001838  0.000706
2004-12-06  0.049458  0.003730 -0.002523 -0.000772
2004-12-07 -0.044086 -0.009496 -0.008738 -0.011073
2004-12-08  0.006361  0.010838  0.006495  0.004877
2004-12-09  0.011378 -0.004948  0.005992  0.005436
2004-12-10  0.018125 -0.005387 -0.003436 -0.001043
2004-12-13 -0.003683  0.006250  0.010345  0.008990
2004-12-14  0.005853 -0.000828 -0.000228  0.003921
2004-12-15 -0.000613 -0.004144 -0.002959  0.001945
2004-12-16  0.020533  0.001665 -0.007989 -0.002082
2004-12-17 -0.024324 -0.007478 -0.005983 -0.007488
2004-12-20 -0.034780 -0.000419  0.025231  0.000377
2004-12-21  0.015306  0.004606  0.012192  0.009040
2004-12-22  0.001256 -0.003752 -0.007584  0.003418
2004-12-23  0.004078  0.001674  0.013261  0.000463
2004-12-27 -0.013433 -0.006266 -0.021074 -0.004305
2004-12-28  0.016149  0.003783  0.003399  0.007154
2004-12-29  0.004051 -0.001675  0.001581 -0.000074
2004-12-30  0.005587 -0.005034 -0.002029  0.000082
2004-12-31 -0.006173 -0.001686  0.004519 -0.001343

[252 rows x 4 columns]

2005
                AAPL      MSFT       XOM       SPX
2005-01-03 -0.017081  0.000845 -0.022717 -0.008119
2005-01-04  0.010111  0.003797 -0.006904 -0.011671
2005-01-05  0.008758 -0.002522 -0.005098 -0.003628
2005-01-06  0.000930 -0.000843  0.012579  0.003506
2005-01-07  0.072491 -0.002952 -0.006441 -0.001431
2005-01-10 -0.004044  0.004653  0.003705  0.003423
2005-01-11 -0.063805 -0.002526 -0.002537 -0.006100
2005-01-12  0.013941  0.001688  0.014801  0.003981
2005-01-13  0.066300 -0.018963 -0.000684 -0.008630
2005-01-14  0.005731 -0.005584  0.010262  0.006005
2005-01-18  0.006553  0.007775  0.008352  0.009675
2005-01-19 -0.011039 -0.013288 -0.008731 -0.009490
2005-01-20  0.008300 -0.004344 -0.006549 -0.007783
2005-01-21  0.000284 -0.008290 -0.005456 -0.006415
2005-01-24  0.003973  0.000880  0.013714 -0.003528
2005-01-25  0.018372  0.013626  0.003833  0.004004
2005-01-26  0.002498 -0.000434  0.007188  0.004844
2005-01-27  0.005537  0.003905  0.001115  0.000409
2005-01-28  0.018447  0.002593 -0.009356 -0.002716
2005-01-31  0.039470  0.003879  0.006521  0.008460
2005-02-01  0.008062  0.004294  0.032395  0.006891
2005-02-02  0.027090  0.002565  0.012335  0.003178
2005-02-03 -0.022859 -0.010661  0.010902 -0.002766
2005-02-04  0.013368  0.005603  0.014168  0.011043
2005-02-07  0.001268 -0.006429  0.001877 -0.001089
2005-02-08  0.024829  0.003020  0.011863  0.000483
2005-02-09 -0.026700 -0.006452 -0.004319 -0.008575
2005-02-10 -0.004826 -0.000433  0.014460  0.004211
2005-02-11  0.036243 -0.003032 -0.004072  0.006926
2005-02-14  0.042118  0.001303  0.012676  0.000697
...              ...       ...       ...       ...
2005-11-17 -0.006620  0.008441  0.003360  0.009414
2005-11-18  0.000620  0.003587  0.015166  0.004401
2005-11-21  0.006196  0.003177  0.019208  0.005271
2005-11-22  0.024015 -0.008709  0.004950  0.005084
2005-11-23  0.008870  0.000399  0.003599  0.003473
2005-11-25  0.033229 -0.005988  0.003964  0.002086
2005-11-28  0.004615 -0.000402 -0.022749 -0.008508
2005-11-29 -0.022394 -0.002411 -0.006926  0.000016
2005-11-30 -0.004112  0.000000 -0.005231 -0.006362
2005-12-01  0.055736  0.007652  0.022785  0.012157
2005-12-02  0.014385  0.004396 -0.004760  0.000324
2005-12-05 -0.011152 -0.005969  0.007461 -0.002363
2005-12-06  0.031050 -0.005604  0.003038  0.001276
2005-12-07 -0.001350  0.002013 -0.011359 -0.005009
2005-12-08  0.001758 -0.002009  0.006894 -0.001217
2005-12-09  0.003375  0.000805 -0.015595  0.002811
2005-12-12  0.007803 -0.009654  0.006182  0.000842
2005-12-13  0.000934 -0.011373  0.003456  0.005554
2005-12-14 -0.039611 -0.001643  0.013586  0.004190
2005-12-15  0.002361 -0.006173 -0.006230 -0.001414
2005-12-16 -0.014824 -0.000828 -0.024126 -0.002848
2005-12-19  0.003797 -0.002487 -0.006035 -0.005839
2005-12-20  0.010227  0.000831  0.003917 -0.000238
2005-12-21  0.019276 -0.004566 -0.005657  0.002517
2005-12-22  0.007075 -0.005421 -0.008633  0.004221
2005-12-23 -0.009052  0.002096  0.000000  0.000426
2005-12-27  0.011997 -0.006695 -0.021571 -0.009553
2005-12-28 -0.008891 -0.002949  0.006675  0.001297
2005-12-29 -0.028816 -0.004225 -0.000201 -0.002981
2005-12-30  0.006158 -0.004667 -0.001206 -0.004887

[252 rows x 4 columns]

2006
                AAPL      MSFT       XOM       SPX
2006-01-03  0.039783  0.026428  0.041046  0.016430
2006-01-04  0.002943  0.004568  0.001739  0.003673
2006-01-05 -0.007870  0.000827 -0.005016  0.000016
2006-01-06  0.025813 -0.002891  0.019779  0.009399
2006-01-09 -0.003277 -0.002071 -0.000570  0.003656
2006-01-10  0.063248  0.005396  0.007801 -0.000357
2006-01-11  0.037596  0.010735  0.006796  0.003481
2006-01-12  0.004648 -0.005310 -0.010501 -0.006274
2006-01-13  0.015423  0.001643  0.022361  0.001205
2006-01-17 -0.010282 -0.007380  0.009268 -0.003557
2006-01-18 -0.026207 -0.005783 -0.013958 -0.003975
2006-01-19 -0.041823  0.007063  0.013597  0.005564
2006-01-20 -0.037323 -0.022690 -0.015803 -0.018326
2006-01-23  0.020765 -0.002111  0.011016  0.001847
2006-01-24 -0.020986 -0.002961 -0.003878  0.002405
2006-01-25 -0.024198  0.004667 -0.012236 -0.001721
2006-01-26 -0.025202  0.003801 -0.004317  0.007235
2006-01-27 -0.004148  0.048801  0.022243  0.007764
2006-01-30  0.041233  0.007621  0.029688  0.001145
2006-01-31  0.006800  0.005175 -0.005731 -0.003976
2006-02-01 -0.001192 -0.003960 -0.012608  0.001859
2006-02-02 -0.044020 -0.012724  0.000000 -0.009061
2006-02-03 -0.003467 -0.005236 -0.009121 -0.005359
2006-02-06 -0.063326 -0.013360  0.009389  0.000783
2006-02-07  0.004458 -0.008207 -0.022798 -0.008095
2006-02-08  0.017899 -0.001241  0.002613  0.008663
2006-02-09 -0.056096 -0.009114 -0.007818 -0.001478
2006-02-10  0.036336  0.000836 -0.008068  0.002540
2006-02-13 -0.038627 -0.011278  0.002837 -0.003260
2006-02-14  0.045279  0.010139 -0.000943  0.010033
...              ...       ...       ...       ...
2006-11-16  0.018560  0.012075 -0.028457  0.002284
2006-11-17  0.002803 -0.002610  0.005645  0.001029
2006-11-20  0.007222  0.016822 -0.008799 -0.000500
2006-11-21  0.024633  0.001103  0.013162  0.001649
2006-11-22  0.019300  0.000000 -0.006495  0.002338
2006-11-24  0.014616 -0.005509 -0.007298 -0.003656
2006-11-27 -0.022809 -0.009232  0.001225 -0.013555
2006-11-28  0.025352 -0.002982  0.023405  0.003444
2006-11-29 -0.000109  0.005981  0.025112  0.009202
2006-11-30 -0.001525 -0.007061  0.010353  0.000822
2006-12-01 -0.003709 -0.008234  0.005051 -0.002799
2006-12-04 -0.002190  0.007170  0.007323  0.008885
2006-12-05  0.001646 -0.006744  0.003849  0.004002
2006-12-06 -0.015777 -0.004904 -0.022437 -0.001315
2006-12-07 -0.031059 -0.004928 -0.007844 -0.003971
2006-12-08  0.014017  0.019048 -0.002782  0.001812
2006-12-11  0.005552  0.004860 -0.001909  0.002270
2006-12-12 -0.029408 -0.003720  0.011768 -0.001047
2006-12-13  0.033782  0.004108  0.014539  0.001169
2006-12-14 -0.005615  0.017479  0.017770  0.008689
2006-12-15 -0.009373  0.004020 -0.018164  0.001122
2006-12-18 -0.025650 -0.009829 -0.023089 -0.003230
2006-12-19  0.009828  0.003309  0.019524  0.002158
2006-12-20 -0.017959  0.003298 -0.011807 -0.001417
2006-12-21 -0.021944 -0.003652 -0.002768 -0.003674
2006-12-22 -0.008444 -0.011364 -0.005991 -0.005316
2006-12-26 -0.008394  0.011865  0.008379  0.004352
2006-12-27  0.000123  0.001099  0.011953  0.007015
2006-12-28 -0.007974 -0.001464  0.004898 -0.001479
2006-12-29  0.049091 -0.004032 -0.009031 -0.004513

[251 rows x 4 columns]

2007
                AAPL      MSFT       XOM       SPX
2007-01-03 -0.012258  0.000000 -0.032981 -0.001199
2007-01-04  0.022196 -0.001472 -0.018699  0.001228
2007-01-05 -0.007121 -0.005898  0.007165 -0.006085
2007-01-08  0.004938  0.010011 -0.008022  0.002220
2007-01-09  0.083070  0.000734 -0.007782 -0.000517
2007-01-10  0.047856 -0.009905 -0.015224  0.001940
2007-01-11 -0.012371  0.035198 -0.000156  0.006340
2007-01-12 -0.012317  0.016464  0.023583  0.004853
2007-01-16  0.026210 -0.001408 -0.014037  0.000818
2007-01-17 -0.022142 -0.002116  0.011452 -0.000894
2007-01-18 -0.061927 -0.003180 -0.006885 -0.002971
2007-01-19 -0.006399  0.003545  0.021876  0.002895
2007-01-22 -0.019322 -0.012363 -0.008593 -0.005278
2007-01-23 -0.012559  0.000358  0.021898  0.003542
2007-01-24  0.011669  0.011441  0.005506  0.008501
2007-01-25 -0.005190 -0.020502 -0.018499 -0.011270
2007-01-26 -0.010087  0.005052  0.001206 -0.001208
2007-01-29  0.006559 -0.002513 -0.005572 -0.001097
2007-01-30 -0.004538 -0.001440  0.016356  0.005772
2007-01-31  0.002104  0.012257 -0.004023  0.006593
2007-02-01 -0.011548 -0.009615  0.013315  0.005354
2007-02-02  0.000118 -0.012226  0.006053  0.001694
2007-02-05 -0.009558 -0.018930  0.001761 -0.000967
2007-02-06  0.002502 -0.003711 -0.002783  0.000698
2007-02-07  0.023767 -0.004469 -0.004701  0.001395
2007-02-08  0.000348 -0.003741  0.009004 -0.001179
2007-02-09 -0.033767 -0.009763 -0.003218 -0.007077
2007-02-12  0.019335 -0.001138 -0.008218 -0.003261
2007-02-13 -0.002121  0.005695  0.011394  0.007597
2007-02-14  0.007084  0.013590  0.002048  0.007644
...              ...       ...       ...       ...
2007-11-16  0.012721  0.009634  0.007228  0.005230
2007-11-19 -0.014664 -0.003817 -0.011661 -0.017460
2007-11-20  0.029887  0.018519  0.044081  0.004486
2007-11-21 -0.002310 -0.010345 -0.008817 -0.015927
2007-11-23  0.018283 -0.003484  0.014282  0.016891
2007-11-26  0.005830 -0.033376 -0.029521 -0.023239
2007-11-27  0.013156  0.002631  0.008146  0.014930
2007-11-28  0.030948  0.019351  0.017801  0.028560
2007-11-29  0.022584 -0.003218  0.007690  0.000477
2007-11-30 -0.011232  0.000323  0.006401  0.007770
2007-12-03 -0.018439 -0.020329 -0.003425 -0.005887
2007-12-04  0.005311 -0.004282 -0.008223 -0.006540
2007-12-05  0.031645  0.042011  0.020418  0.015190
2007-12-06  0.023989  0.011746  0.016857  0.015037
2007-12-07  0.022901 -0.000628  0.000716 -0.001778
2007-12-10 -0.000463  0.006593  0.005720  0.007510
2007-12-11 -0.029195 -0.019027 -0.018960 -0.025271
2007-12-12  0.012305  0.010811  0.018118  0.006050
2007-12-13  0.005082  0.022020  0.008779  0.001224
2007-12-14 -0.007507  0.002462 -0.016700 -0.013746
2007-12-17 -0.031462 -0.026098 -0.014113 -0.015021
2007-12-18 -0.007701  0.010088  0.016984  0.006280
2007-12-19  0.000765  0.001561  0.000119 -0.001361
2007-12-20  0.022335  0.020879  0.007634  0.004900
2007-12-21  0.035789  0.015263  0.014205  0.016670
2007-12-24  0.025218  0.014432  0.002451  0.008077
2007-12-26  0.000755  0.000889  0.012225  0.000809
2007-12-27 -0.001910 -0.017471 -0.011962 -0.014282
2007-12-28  0.006345  0.004219  0.014203  0.001504
2007-12-31 -0.008757 -0.014406 -0.013889 -0.006852

[251 rows x 4 columns]

2008
                AAPL      MSFT       XOM       SPX
2008-01-02 -0.016357 -0.010658 -0.001862 -0.014438
2008-01-03  0.000462  0.004001  0.003382  0.000000
2008-01-04 -0.076335 -0.027897 -0.018596 -0.024552
2008-01-07 -0.013385  0.006623 -0.009356  0.003223
2008-01-08 -0.035972 -0.033521 -0.012791 -0.018352
2008-01-09  0.047591  0.029822  0.016711  0.013624
2008-01-10 -0.007692 -0.003148  0.001072  0.007948
2008-01-11 -0.029940 -0.012314 -0.014753 -0.013595
2008-01-14  0.035266  0.014066  0.005796  0.010871
2008-01-15 -0.054480 -0.011349 -0.019930 -0.024925
2008-01-16 -0.055608 -0.022640 -0.027931 -0.005612
2008-01-17  0.007830 -0.003589 -0.030246 -0.029093
2008-01-18  0.002921 -0.002947  0.013905 -0.006045
2008-01-22 -0.035449 -0.031856 -0.030890 -0.011085
2008-01-23 -0.106464 -0.001018  0.012035  0.021442
2008-01-24 -0.024951  0.041426  0.030580  0.010063
2008-01-25 -0.041224 -0.009455 -0.023967 -0.015872
2008-01-28  0.000000 -0.006583  0.014291  0.017548
2008-01-29  0.011768 -0.003645 -0.000640  0.006160
2008-01-30  0.004865 -0.012305  0.002307 -0.004764
2008-01-31  0.024058  0.012458  0.004987  0.016772
2008-02-01 -0.011894 -0.065846  0.002927  0.012237
2008-02-04 -0.015701 -0.008544 -0.005963 -0.010463
2008-02-05 -0.017395 -0.037343 -0.038928 -0.031995
2008-02-06 -0.056895 -0.018650 -0.008234 -0.007624
2008-02-07 -0.006230 -0.014063  0.009909  0.007886
2008-02-08  0.034972  0.015420 -0.002254 -0.004204
2008-02-11  0.031639 -0.012149  0.018472  0.005889
2008-02-12 -0.035458  0.004612  0.013961  0.007266
2008-02-13  0.036361  0.021806  0.013126  0.013604
...              ...       ...       ...       ...
2008-11-18  0.020082  0.022185  0.040222  0.009838
2008-11-19 -0.040262 -0.067824 -0.038106 -0.061156
2008-11-20 -0.067215 -0.041327 -0.066851 -0.067123
2008-11-21  0.025966  0.122647  0.106446  0.063248
2008-11-24  0.125575  0.051379  0.039498  0.064723
2008-11-25 -0.023131 -0.033951 -0.008685  0.006551
2008-11-26  0.046256  0.025027  0.035455  0.035328
2008-11-28 -0.024526 -0.013506 -0.009122  0.009643
2008-12-01 -0.040358 -0.079516 -0.072849 -0.089295
2008-12-02  0.039807  0.029176  0.044467  0.039941
2008-12-03  0.037093  0.037799  0.016947  0.025836
2008-12-04 -0.046820 -0.038565 -0.033735 -0.029308
2008-12-05  0.028334  0.040111  0.004347  0.036499
2008-12-08  0.060851  0.057311  0.039229  0.038387
2008-12-09  0.003410 -0.019757 -0.017598 -0.023118
2008-12-10 -0.018489  0.000517  0.023930  0.011894
2008-12-11 -0.032685 -0.056302 -0.000668 -0.028524
2008-12-12  0.034421 -0.004379  0.005345  0.007028
2008-12-15 -0.035820 -0.016493 -0.006115 -0.012686
2008-12-16  0.007177  0.055897  0.039856  0.051360
2008-12-17 -0.065703 -0.022234 -0.025080 -0.009593
2008-12-18  0.003028 -0.018408 -0.050000 -0.021163
2008-12-19  0.006374 -0.009377 -0.025691  0.002937
2008-12-22 -0.047333  0.003341 -0.001568 -0.018302
2008-12-23  0.007464  0.004994  0.002570 -0.009717
2008-12-24 -0.015513 -0.005522  0.009113  0.005781
2008-12-26  0.009055 -0.002221  0.018485  0.005356
2008-12-29  0.009323 -0.008904  0.010806 -0.003873
2008-12-30 -0.003695  0.020213  0.007264  0.024407
2008-12-31 -0.010893  0.004953  0.015784  0.014158

[253 rows x 4 columns]

2009
                AAPL      MSFT       XOM       SPX
2009-01-02  0.063269  0.046002  0.022773  0.031608
2009-01-05  0.042204  0.009424 -0.000131 -0.004668
2009-01-06 -0.016494  0.011411 -0.016374  0.007817
2009-01-07 -0.021608 -0.060000 -0.025436 -0.030010
2009-01-08  0.018569  0.031097  0.010659  0.003397
2009-01-09 -0.022869 -0.029630 -0.019200 -0.021303
2009-01-12 -0.021197 -0.002726 -0.013234 -0.022564
2009-01-13 -0.010715  0.018043  0.018022  0.001758
2009-01-14 -0.027135 -0.037057 -0.036229 -0.033460
2009-01-15 -0.022852  0.007808  0.020789  0.001329
2009-01-16 -0.012593  0.024903  0.018831  0.007562
2009-01-20 -0.050164 -0.062635 -0.023275 -0.052816
2009-01-21  0.059207  0.048963  0.038968  0.043491
2009-01-22  0.066763 -0.117518 -0.012952 -0.015162
2009-01-23  0.000000  0.005600 -0.002460  0.005378

In [8]:
spx_corr = lambda x: x.corrwith(x['SPX'])
by_year.apply(spx_corr)

          AAPL      MSFT       XOM  SPX
2003  0.541124  0.745174  0.661265  1.0
2004  0.374283  0.588531  0.557742  1.0
2005  0.467540  0.562374  0.631010  1.0
2006  0.428267  0.406126  0.518514  1.0
2007  0.508118  0.658770  0.786264  1.0
2008  0.681434  0.804626  0.828303  1.0
2009  0.707103  0.654902  0.797921  1.0
2010  0.710105  0.730118  0.839057  1.0
2011  0.691931  0.800996  0.859975  1.0

我们也可以计算列内的相关性。这里我们计算苹果和微软每年的相关性：

In [11]:
by_year.apply(lambda g: g['AAPL'].corr(g['MSFT']))

2003    0.480868
2004    0.259024
2005    0.300093
2006    0.161735
2007    0.417738
2008    0.611901
2009    0.432738
2010    0.571946
2011    0.581987
dtype: float64

# 9.3.6 例子：组对组的线性回归

In [12]:
import statsmodels.api as sm

E:\software\anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

现在，按年用苹果AAPL在标普SPX上做线性回归：

In [13]:
def regress(data, yvar, xvars):
    Y = data[yvar]
    X = data[xvars]
    X['intercept'] = 1
    result = sm.OLS(Y, X).fit()
    return result.params

by_year.apply(regress, 'AAPL', ['SPX'])

           SPX  intercept
2003  1.195406   0.000710
2004  1.363463   0.004201
2005  1.766415   0.003246
2006  1.645496   0.000080
2007  1.198761   0.003438
2008  0.968016  -0.001110
2009  0.879103   0.002954
2010  1.052608   0.001261
2011  0.806605   0.001514